Feat/login
STA-Development/Social_Network_Inter pull request #1
Opened 2024-03-25 21:01 UTC by vahea95

2024-03-25 23:23 UTC, ArthurO2002 requested changes

2024-03-25 23:23 UTC, ArthurO2002 commented on src/Components/Profile.tsx
> +      }
Remove logs and comments

2024-03-25 23:23 UTC, ArthurO2002 commented on src/Components/Profile.tsx
> +  }
Remove comments

2024-03-25 23:23 UTC, ArthurO2002 commented on src/Components/Profile.tsx
> +  if (user !== null) {
Dellete this component it's not making any sense

2024-03-25 23:23 UTC, ArthurO2002 commented on public/index.html
>    </body>
Remove

2024-03-25 23:23 UTC, ArthurO2002 commented on .gitignore
> +.idea
```suggestion

// Intelij
.idea
```

2024-03-26 15:06 UTC, vahea95 commented on src/Components/Profile.tsx
> +      }
done

2024-03-26 15:06 UTC, vahea95 commented on .gitignore
> +.idea
done

2024-03-26 15:06 UTC, vahea95 commented on public/index.html
>    </body>
done

2024-03-26 15:06 UTC, vahea95 commented on src/Components/Profile.tsx
> +  if (user !== null) {
done

2024-03-26 15:06 UTC, vahea95 commented on src/Components/Profile.tsx
> +  }
done

2024-03-26 17:47 UTC, ArthurO2002 approved these changes

2024-03-26 17:47 UTC, ArthurO2002 requested changes

2024-03-26 17:47 UTC, ArthurO2002 commented on .env
> +REACT_APP_API_URL=http://192.168.1.133:5000/api
ENV should not be pushed

2024-03-26 17:59 UTC, vahea95 commented on .env
> +REACT_APP_API_URL=http://192.168.1.133:5000/api
done

2024-03-26 18:05 UTC, ArthurO2002 approved these changes

2024-03-26 18:05 UTC, merged